version: 0.2

# from environment variables
# ECR_NAME=...
# DOCKER_USERNAME=...
# DOCKER_TOKEN=...

phases:
  pre_build:
    commands:
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH}

  build:
    commands:
      - docker login --username $DOCKER_USERNAME --password $DOCKER_TOKEN

      - docker build
        --target bsky-feed-bot-lambda
        -t ${ECR_NAME}/bsky-feed-bot-lambda:latest
        -t ${ECR_NAME}/bsky-feed-bot-lambda:${IMAGE_TAG}
        -f Dockerfile .

  post_build:
    commands:
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION |
        docker login --username AWS --password-stdin $ECR_NAME

      - docker push ${ECR_NAME}/bsky-feed-bot-lambda:latest
      - docker push ${ECR_NAME}/bsky-feed-bot-lambda:${IMAGE_TAG}
